### ISSUE TITLE
Undefined symbols for architecture x86_64 / i386

### ISSUE THREAD

**Issue by hibento** [krzyzanowskim/CryptoSwift#149]
Hi,

with a release > 0.0.16 Xcode fails to build our project. Seems there're some symbols missing. Are there any changes regarding a hash for a string? I'm using

    "Example".sha256()

works fine in version 0.0.16, but any new version throws an error during compiling:
  
    Undefined symbols for architecture x86_64:
    "ext.CryptoSwift.Swift.String.sha256 (Swift.String)() -> Swift.String?", referenced from:
    static myProject.myClass.myObject.getter : myProject.myClass in myClass.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm building the framework using carthage (latest version and cleared the cache before building).

**Comment by krzyzanowskim** [comment]
this function do not return an Optional so ¯\\_(ツ)_/¯ maybe delete derived data.

```swift
func sha256() -> String
```

**Comment by hibento** [comment]
You're right. I cleaned the Project several times, still Xcode thinks sha256() returns an optional.

![Xcode ignores clean](http://s12.postimg.org/gi19ln37h/2015_10_15_at_15_24.png)

**Comment by krzyzanowskim** [comment]
maybe Carthage left some files from the previous version

**Comment by hibento** [comment]
Deleted carthage cache (again), build frameworks (again) and delete derived data from Xcode (new) and now it works
<img src="http://s16.postimg.org/tb8e40yxh/homer_woohoo.jpg" width="200">

Thanks a lot.

**Comment by krzyzanowskim** [comment]
magic huh? :)
