### ISSUE TITLE
Error Compiling BatchedCollection.swift on Ubuntu Swift 4.0.3

### ISSUE THREAD

**Issue by mowais786** [krzyzanowskim/CryptoSwift#604]
- CryptoSwift version: Latest
- Swift version: 4.0.3
- Platform (iLinux/Ubuntu): 
- Installation method (SPM): 

swiftc BatchedCollection.swift 
BatchedCollection.swift:39:21: error: no 'index' candidates produce the expected contextual result type '_?'
        return base.index(idx, offsetBy: size, limitedBy: base.endIndex)
                    ^
BatchedCollection.swift:39:21: note: overloads for 'index' exist with these result types: Self.Index, Self.Index?
        return base.index(idx, offsetBy: size, limitedBy: base.endIndex)

**Comment by krzyzanowskim** [comment]
0.9 is Swift 4.1 compatible

**Comment by mowais786** [comment]
I am novice to Swift can you help me to change this so that it compile with 4.0.03

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/CryptoSwift#swift-package-manager

```swift
dependencies: [
    .package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", .exact("0.8.3"))
]
```
