### ISSUE TITLE
Cannot compile with Jenkins using 0.6.8

### ISSUE THREAD

**Issue by zeusent** [krzyzanowskim/CryptoSwift#418]
Since updating to version `0.6.8` compilation via Jenkins fails with these errors in `AES.swift`:

```
/Users/jenkins/Jenkins/jobs/[MY_PROJECT]/workspace/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:142:179: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
        var b0 = UInt32(block[block.startIndex + 0 + (0 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (0 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (0 << 2)]) << 16 | UInt32(block[block.startIndex + 3 + (0 << 2)]) << 24
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jenkins/Jenkins/jobs/[MY_PROJECT]/workspace/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:143:179: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
        var b1 = UInt32(block[block.startIndex + 0 + (1 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (1 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (1 << 2)]) << 16 | UInt32(block[block.startIndex + 3 + (1 << 2)]) << 24
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jenkins/Jenkins/jobs/[MY_PROJECT]/workspace/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:144:179: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
        var b2 = UInt32(block[block.startIndex + 0 + (2 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (2 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (2 << 2)]) << 16 | UInt32(block[block.startIndex + 3 + (2 << 2)]) << 24
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jenkins/Jenkins/jobs/[MY_PROJECT]/workspace/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:145:179: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
        var b3 = UInt32(block[block.startIndex + 0 + (3 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (3 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (3 << 2)]) << 16 | UInt32(block[block.startIndex + 3 + (3 << 2)]) << 24
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

And this one in `MD5.swift`

```
/Users/jenkins/Jenkins/jobs/[MY_PROJECT]/workspace/Pods/CryptoSwift/Sources/CryptoSwift/MD5.swift:96:179: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
            let Mg = UInt32(chunk[chunk.startIndex + gAdvanced]) | UInt32(chunk[chunk.startIndex + gAdvanced &+ 1]) << 8 | UInt32(chunk[chunk.startIndex + gAdvanced &+ 2]) << 16 | UInt32(chunk[chunk.startIndex + gAdvanced &+ 3]) << 24
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I've reverted back to `0.6.7` and everything is fine though I wish this would be fixed.

**Comment by krzyzanowskim** [comment]
Omg. Uh. The quick fix is: you need the faster computer because the "reasonable time" for swift compiler depends on the machine ;))))

I'll take this into account and split the line to make the compiler happy

**Comment by shujaathaider** [comment]
I am getting same issue in CircleCI.

**Comment by krzyzanowskim** [comment]
Can you please verify if the develop builds now?

**Comment by dai-cb** [comment]
Tested `develop` on CircleCI - still issues:

```
❌  /Users/distiller/coinbase-ios/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:142:124: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

        var b0 = UInt32(block[block.startIndex + 0 + (0 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (0 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (0 << 2)]) << 16
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



❌  /Users/distiller/coinbase-ios/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:144:124: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

        var b1 = UInt32(block[block.startIndex + 0 + (1 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (1 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (1 << 2)]) << 16
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



❌  /Users/distiller/coinbase-ios/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:146:124: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

        var b2 = UInt32(block[block.startIndex + 0 + (2 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (2 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (2 << 2)]) << 16
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



❌  /Users/distiller/coinbase-ios/Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:148:124: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

        var b3 = UInt32(block[block.startIndex + 0 + (3 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (3 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (3 << 2)]) << 16
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by zeusent** [comment]
I think this is happening because Swift takes to long to infer the type of the variable. Do you think that maybe declaring it as UInt32 before assignement would help?

So maybe instead of having things like 'var b0 = ...' change it to 'var b0: UInt32 = ...'?

**Comment by zeusent** [comment]
Just a little bit more info about this. It seems that this guy [here](http://stackoverflow.com/questions/29707622/bizarre-swift-compiler-error-expression-too-complex-on-a-string-concatenation/29931329#29931329) has some detailed informations about the problem. He also points to a similar problem on Apple's forums [here](https://devforums.apple.com/message/1097960#1097960).

He is saying that Apple's engineers are asking people to submit issues like this so they can fix accordingly. So maybe a Radar report would be helpful for them and us in the long run.

**Comment by krzyzanowskim** [comment]
yeap, I know the reason, it's just dependant on the machine where it is processed. Like, on my MacBook it compiles fine, but on slow machines, it may think it takes too much time. And you newer know which part will take too much time.

it's just unpredictable ;-(

**Comment by zeusent** [comment]
Well on my 4 years old MacBook compiles fine. My Jenkins runs on a 1 and a half years old Mac Pro and it fails :( (the round desktop machine from Apple, so it's not really the slowest machine :) ). So that is weird.

**Comment by krzyzanowskim** [comment]
Looks like the most realiable workaround is to add this to Swift compiler flags:
`-Xfrontend -solver-memory-threshold -Xfrontend <some big number>`
